SMFIScholarshipSystem/Models/Interviewers.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMFIScholarshipSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interviewers
    {
        public int InID { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string Designation { get; set; }
    }
}

SMFIScholarshipSystem/Controllers/InterviewerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMScholars.BLL;
using SMFIScholarshipSystem.Models;

namespace SMFIScholarshipSystem.Controllers
{
    public class InterviewerController : Controller
    {
        // GET: Interviewer
 
        public ActionResult Index()
        {
            return View();
        }
       
        // Insert Interviewer
        [HttpPost]
        public ActionResult AddInterviewer(smuser i)
        {
            try
            {
                smscholarsEntities smfi = new smscholarsEntities();
                smuser newInterviewer = new smuser();

                var encryptPass = CustomEnrypt.Encrypt(i.Password);
                newInterviewer.InID = i.InID;
                newInterviewer.Name = i.Name;
                newInterviewer.Company = i.Company;
                newInterviewer.Designation = i.Designation;
                newInterviewer.Username = i.Username;
                newInterviewer.Email = i.Email;
                newInterviewer.Password = encryptPass;
                newInterviewer.Position = i.Position;
                newInterviewer.ContactNumber = i.ContactNumber;
                smfi.smusers.Add(newInterviewer);
                smfi.SaveChanges();              
                return Json(new { Result = "OK", Record = newInterviewer });
            }
            catch (Exception ex)
            {

                return Json(new { result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }

        }
        [HttpPost]
        public ActionResult UpdateInterviewer(smuser i)
        {
            try
            {
                smscholarsEntities smfi = new smscholarsEntities();
                smuser newInter = smfi.smusers.Where(x => x.InID == i.InID).FirstOrDefault();
                if (newInter == null)
                {
                    throw new Exception("Interviewer not found!");
                }

                newInter.InID = i.InID;
                newInter.Name = i.Name;
                newInter.Company = i.Company;
                newInter.Designation = i.Designation;
                newInter.ContactNumber = i.ContactNumber;

                smfi.SaveChanges();

                InterviewModel im = new InterviewModel();
                im.InID = newInter.InID;
                im.Name = newInter.Name;
                im.Company = newInter.Company;
                im.Designation = newInter.Designation;
                im.ContactNumber = newInter.ContactNumber;
                return Json(new { Result = "OK", Record = im });

            }
            catch (Exception ex)
            {

                return Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }        
        }
        [HttpPost]
        public ActionResult DeleteInterviewer(smuser i)
        {
            try
            {
                smscholarsEntities smfi = new smscholarsEntities();
                smuser newInter = smfi.smusers.Where(x => x.InID == i.InID).FirstOrDefault();
                if (newInter == null)
                {
                    throw new Exception("Interviewer not found!");
                }
                smfi.smusers.Remove(newInter);
                smfi.SaveChanges();

                return Json(new { Result = "OK"});

            }
            catch (Exception ex)
            {

                return Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
       
        
    }
}

SMFIScholarshipSystem/Controllers/ReligionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMScholars.BLL;

namespace SMFIScholarshipSystem.Controllers
{
    public class ReligionController : Controller
    {
        smscholarsEntities sm = new smscholarsEntities();    
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddReligion(religion rg)
        {
            try
            {
                religion newRg = new religion();
                newRg.Name = rg.Name;
                    sm.religions.Add(newRg);
                sm.SaveChanges();
                return Json(new { Result = "OK", Record = newRg });

            }
            catch (Exception ex)
            {

                return Json(new { result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult UpdateReligion(religion rg)
        {
            try
            {
                religion newRg = sm.religions.Where(x => x.ReligionID == rg.ReligionID).FirstOrDefault();
                newRg.ReligionID = rg.ReligionID;
                newRg.Name = rg.Name;
                sm.SaveChanges();
                ReligionModel newRgModel = new ReligionModel();
                newRgModel.Name = newRg.Name;
                newRgModel.ReligionID = newRg.ReligionID;
                return Json(new { Result = "OK", Record = newRgModel });

            }
            catch (Exception ex)
            {

                return Json(new { result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult DeleteReligion(religion rg)
        {
            try
            {
                religion newRg = sm.religions.Where(x => x.ReligionID == rg.ReligionID).FirstOrDefault();
                if (newRg == null)
                {
                    throw new Exception("No Religion Found");
                }
                sm.religions.Remove(newRg);
                sm.SaveChanges();

                return Json(new { Result = "OK" });

            }
            catch (Exception ex)
            {

                return Json(new { result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SMFIScholarshipSystem/Controllers/SchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMScholars.BLL;

namespace SMFIScholarshipSystem.Controllers
{
    public class SchoolController : Controller
    {
        // GET: School
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddSchool(school skool)
        {
            try
            {
                smscholarsEntities smfi = new smscholarsEntities();
                school skul = new school();
                skul.SchoolID = skool.SchoolID;
                skul.SchoolName = skool.SchoolName;
                smfi.schools.Add(skul);
                smfi.SaveChanges();
                return Json(new { Result = "OK", Record = skul });
                
            }
            catch (Exception ex)
            {

                return Json(new { result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            //return Json
        }
        [HttpPost]
        public ActionResult UpdateSchool(school skool)
        {
            try
            {
                smscholarsEntities smfi = new smscholarsEntities();
                school skul = smfi.schools.Where(x => x.SchoolID == skool.SchoolID).FirstOrDefault();
                skul.SchoolID = skool.SchoolID;
                skul.SchoolName = skool.SchoolName;
                smfi.SaveChanges();
                SchoolModel scModel = new SchoolModel();
                scModel.SchoolID = skul.SchoolID;
                scModel.SchoolName = skul.SchoolName;
                return Json(new { Result = "OK", Record = scModel });


            }
            catch (Exception ex)
            {
                
                 return Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult DeleteSchool(school skool)
        {
            try
            {
                smscholarsEntities smfi = new smscholarsEntities();
                school skul = smfi.schools.Where(x => x.SchoolID == skool.SchoolID).FirstOrDefault();
                if (skul == null)
                {
                    throw new Exception("School Type not found!");
                }
                smfi.schools.Remove(skul);
                smfi.SaveChanges();

                return Json(new { Result = "OK" });

            }
            catch (Exception ex)
            {

                return Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

    }
}

SMFIScholarshipSystem/Views/Shared/_Admin.cshtml
    @Styles.Render("~/Content/sss")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        
        body{margin-top:50px;
       

        }
.glyphicon { margin-right:10px; }
.panel-body { padding:0px; }
.panel-body table tr td { padding-left: 10px }
.panel-body .table {margin-bottom: 0px; }
    </style>
@{
    var AdminCredential = (SMFIScholarshipSystem.Models.GetAdminCredrentials)Session["AdminCredentials"];
    if (AdminCredential != null)
    {
     <div style="margin-left:2%">
         <div class="row">
             <div class="col-md-2">
                 <br />
                 <br />
                 <div class="panel panel-primary">

                     <div class="panel-heading"><p>Hello, @AdminCredential.AdminFname </p></div>

                     <div class="panel-body">
                         “You are the grand estate and administrator of — now.”
                         ― Bryant McGill
                     </div>
                 </div>
                 <div class="panel-group" id="accordion">

                     <div class="panel panel-default">
                         <div class="panel-heading">
                             <h4 class="panel-title">
                                 <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                     <span class="glyphicon glyphicon-list-alt">
                                     </span> @Html.ActionLink("All Applicants", "ViewAllStudents", "ShowAllStudentAdmin")

                                 </a>

                             </h4>
                         </div>
                         <div id="collapseOne" class="panel-collapse collapse in">
                             <div class="panel-body">
                                 <table class="table">
                                     <tr>
                                         <td>
                                             <span class="glyphicon glyphicon-time"></span>@Html.ActionLink("Pending Student", "Index", "ShowAllStudentAdmin")
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <span class="glyphicon glyphicon-user text-success"></span>@Html.ActionLink("Accepted Applications", "AcceptedStudents", "ShowAllStudentAdmin")
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <span class="glyphicon glyphicon-user text-danger"></span>@Html.ActionLink("Declined Applications", "DeclinedStudents", "ShowAllStudentAdmin")
                                         </td>
                                     </tr>

                                     <tr>
                                         <td>
                                             <span class="glyphicon glyphicon-user text-warning"></span>@Html.ActionLink("Application Approval", "StudentComparison", "ShowAllStudentAdmin")
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <span class="glyphicon glyphicon-file text-info"></span>@Html.ActionLink("Ready for Exam", "ForExamination", "ShowAllStudentAdmin")
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <span class="	glyphicon glyphicon-list-alt text-success text-primary"></span>@Html.ActionLink("Exam Result", "ExamResults", "ShowAllStudentAdmin")
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <span class="glyphicon glyphicon-user"></span>@Html.ActionLink("Applicants For Interview", "interviewResults", "ShowAllStudentAdmin")
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <span class="glyphicon glyphicon-user"></span>@Html.ActionLink("Applicants For Home Visit", "viewinterviewdetails", "ShowAllStudentAdmin")
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <span class="glyphicon glyphicon-user"></span>@Html.ActionLink("Qualified Applicants", "FinalApproval", "ShowAllStudentAdmin")
                                         </td>
                                     </tr>
                                 </table>
                             </div>
                         </div>
                     </div>
                     <div class="panel panel-default">
                         <div class="panel-heading">
                             <h4 class="panel-title">
                                 <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                                     <span class="glyphicon glyphicon-th">
                                     </span>Maintenance
                                 </a>
                             </h4>
                         </div>
                         <div id="collapseTwo" class="panel-collapse collapse">
                             <div class="panel-body">
                                 <table class="table">
                                     <tr>
                                         <td>
                                             <a href="@Url.Action("Index","Interviewer")">SM User</a>
                                         </td>
                                     </tr>

                                     <tr>
                                         <td>
                                             <a href="@Url.Action("Index","QuestionnaireCategory")">Interview Question Category</a>
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <a href="@Url.Action("Index","Questionnaire")">Interview Question</a>
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <a href="@Url.Action("Index","School")">School</a>
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <a href="@Url.Action("Index","MaritalStatus")">Marital Status</a>
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <a href="@Url.Action("Index","Religion")">Religion</a>
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <a href="@Url.Action("Index","EducationalAttainment")">Educational Attainment</a>
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <a href="@Url.Action("Index","AcademicAwardLevel")">Academic Award Level</a>
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <a href="@Url.Action("Index","SchoolCourses")">School Courses</a>
                                         </td>
                                     </tr>
                                 </table>
                             </div>
                         </div>
                     </div>
                     <div class="panel panel-default">
                         <div class="panel-heading">
                             <h4 class="panel-title">
                                 <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                                     <span class="glyphicon glyphicon-user">
                                     </span>Account
                                 </a>
                             </h4>
                         </div>
                         <div id="collapseThree" class="panel-collapse collapse">
                             <div class="panel-body">
                                 <table class="table">
                                     <tr>
                                         <td>
                                             <a href="@Url.Action("LogoutAdmin", "userAuthentication")" class="btn btn-warning">Logout</a>
                                         </td>
                                     </tr>
                                 </table>
                             </div>
                         </div>
                     </div>
                     <div class="panel panel-default">
                         <div class="panel-heading">
                             <h4 class="panel-title">
                                 <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
                                     <span class="glyphicon glyphicon-file">
                                     </span>Reports
                                 </a>
                             </h4>
                         </div>
                         <div id="collapseFour" class="panel-collapse collapse">
                             <div class="panel-body">
                                 <table class="table">
                                     <tr>
                                         <td></td>
                                     </tr>
                                     x
                                 </table>
                             </div>
                         </div>
                     </div>
                     <div class="panel panel-default">
                         <div class="panel-heading">
                             <h4 class="panel-title">
                                 <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
                                     <span class="glyphicon glyphicon-flash">
                                     </span>Standards
                                 </a>
                             </h4>
                         </div>
                         <div id="collapseFive" class="panel-collapse collapse">
                             <div class="panel-body">
                                 <table class="table">
                                     <tr>
                                         <td>
                                             <span class="glyphicon glyphicon-map-marker"></span><a href="@Url.Action("QualifiedArea", "ShowAllStudentAdmin")">Qualified Areas</a>
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <span class="glyphicons glyphicon-euro"></span><a href="@Url.Action("QualifiedIncome", "ShowAllStudentAdmin")">Family Income</a>
                                         </td>
                                     </tr>
                                     <tr>
                                         <td>
                                             <span class="glyphicon glyphicon-th-list"></span><a href="@Url.Action("Qualifiedgwa", "ShowAllStudentAdmin")">GWA</a>
                                         </td>
                                     </tr>

                                 </table>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
             <div class="col-md-10">
                 <div ng-app="MyApplication">
                     <br />
                     <br />
                     @RenderBody()
                 </div>
             </div>
         </div>
     </div>
    
    }

}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    @*<link rel="stylesheet" href="~/Content/bootstrap.min.css">*@

    
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/angular-animate.js"></script>
    <script src="~/Scripts/angular-ui/ui-bootstrap-tpls.min.js"></script>
    <script type="text/javascript" src="~/Scripts/dirPagination.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
   <script src="~/Scripts/angular-aria/angular-aria.min.js"></script>
<script src="~/Scripts/angular-material/angular-material.min.js"></script>
<script src="~/Scripts/angular-messages.min.js"></script>
    <script src="~/Scripts/Startup.js"></script>

    @RenderSection("scripts", required: false)

SMFIScholarshipSystem/Views/Shared/_Approver.cshtml
<div class="container">
    @Styles.Render("~/Content/sss")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            margin-top: 50px;
        }

        .glyphicon {
            margin-right: 10px;
        }

        .panel-body {
            padding: 0px;
        }

            .panel-body table tr td {
                padding-left: 15px;
            }

            .panel-body .table {
                margin-bottom: 0px;
            }
    </style>
    <div class="row">
        <div class="col-sm-3 col-md-3">
            <br />
            <br />
            <div class="panel panel-primary">
                @{
                    var InterviewerCredential = (SMFIScholarshipSystem.Models.GetHomeVisitorCredentials)Session["InterviewerCredentials"];
                    if (InterviewerCredential != null)
                    {
                        <div class="panel-heading"><p>Hello!! @InterviewerCredential.HomeVisitorName </p></div>
                    }

                }
                <div class="panel-body">Approver</div>
            </div>
            <div class="panel-group" id="accordion">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                <span class="glyphicon glyphicon-list-alt">
                                </span>Interview
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-user text-primary"></span>@Html.ActionLink("Students Approval", "Index", "ApproveStatusForStudent")
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="@Url.Action("LogoutInterviewer", "userAuthentication")" onclick="window.location.reload()" class="btn btn-warning">Logout</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-md-9">
            <div ng-app="MyApplication">
                <br />
                <br />
                @RenderBody()
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>*@
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    @*<link rel="stylesheet" href="~/Content/bootstrap.min.css">*@

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/angular-animate.js"></script>
    <script src="~/Scripts/angular-ui/ui-bootstrap-tpls.min.js"></script>
    <script src="~/Scripts/angular-aria/angular-aria.min.js"></script>
    <script src="~/Scripts/angular-material/angular-material.min.js"></script>
    <script src="~/Scripts/angular-messages.min.js"></script>
    <script type="text/javascript" src="~/Scripts/dirPagination.js"></script>
    <script src="~/Scripts/Startup.js"></script>

    @RenderSection("scripts", required: false)
</div>

SMFIScholarshipSystem/Views/Shared/_HomeVisitor.cshtml
<div class="container">
    @Styles.Render("~/Content/sss")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            margin-top: 50px;
        }

        .glyphicon {
            margin-right: 10px;
        }

        .panel-body {
            padding: 0px;
        }

            .panel-body table tr td {
                padding-left: 15px;
            }

            .panel-body .table {
                margin-bottom: 0px;
            }
    </style>
    <div class="row">
        <div class="col-sm-3 col-md-3">
            <br />
            <br />
            <div class="panel panel-primary">
                @{
                    var HomeVisitorCredential = (SMFIScholarshipSystem.Models.GetHomeVisitorCredentials)Session["HomeVisitorCredentials"];
                    if (HomeVisitorCredential != null)
                    {
                        <div class="panel-heading"><p>Hello!! @HomeVisitorCredential.HomeVisitorName </p></div>
                    }

                }
                <div class="panel-body">Home Visitor</div>
            </div>
            <div class="panel-group" id="accordion">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                <span class="glyphicon glyphicon-list-alt">
                                </span>Home Visitor
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-user text-primary"></span>@Html.ActionLink("Home Visit Pending Student", "Index", "InterviewDetails")
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="@Url.Action("LogoutInterviewer", "userAuthentication")" class="btn btn-warning">Logout</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-md-9">
            <div ng-app="MyApplication">
                <br />
                <br />
                @RenderBody()
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>*@
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    @*<link rel="stylesheet" href="~/Content/bootstrap.min.css">*@

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/angular-animate.js"></script>
    <script src="~/Scripts/angular-ui/ui-bootstrap-tpls.min.js"></script>
    <script type="text/javascript" src="~/Scripts/dirPagination.js"></script>
    <script src="~/Scripts/angular-aria/angular-aria.min.js"></script>
    <script src="~/Scripts/angular-material/angular-material.min.js"></script>
    <script src="~/Scripts/angular-messages.min.js"></script>
    <script src="~/Scripts/Startup.js"></script>

    @RenderSection("scripts", required: false)
</div>